In [27]:
import random
nilaitugas = []
for l in range(250):
    nilaitugas.append(random.randrange(1,100,1))
print(nilaitugas)
print("jumlah nilai tugas adalah", len(nilaitugas))

[46, 85, 74, 34, 93, 47, 63, 85, 85, 89, 22, 59, 64, 42, 18, 9, 2, 47, 64, 31, 74, 32, 11, 80, 57, 67, 82, 76, 67, 40, 65, 42, 23, 88, 73, 58, 70, 45, 62, 16, 78, 42, 88, 87, 92, 30, 72, 12, 49, 52, 16, 67, 86, 73, 76, 45, 32, 38, 11, 27, 51, 23, 50, 45, 96, 74, 82, 55, 44, 15, 21, 45, 98, 82, 46, 19, 74, 82, 74, 91, 49, 21, 89, 64, 17, 13, 33, 84, 77, 99, 83, 20, 50, 4, 87, 44, 62, 62, 55, 88, 65, 89, 2, 79, 19, 82, 94, 65, 98, 93, 24, 38, 6, 74, 60, 33, 99, 79, 51, 57, 38, 94, 22, 34, 65, 98, 5, 88, 45, 12, 72, 16, 33, 15, 58, 38, 82, 95, 70, 67, 27, 7, 82, 18, 72, 86, 41, 78, 91, 23, 64, 4, 58, 56, 97, 43, 39, 36, 47, 42, 70, 46, 10, 43, 63, 6, 32, 70, 93, 91, 64, 86, 8, 6, 15, 51, 22, 79, 71, 98, 60, 33, 77, 69, 14, 83, 14, 61, 6, 86, 55, 57, 34, 76, 35, 11, 12, 30, 52, 55, 38, 33, 6, 64, 63, 82, 15, 22, 28, 78, 38, 24, 68, 21, 74, 60, 90, 72, 89, 31, 36, 96, 48, 53, 36, 35, 25, 93, 53, 6, 45, 69, 79, 14, 69, 47, 4, 19, 80, 5, 46, 83, 76, 66, 25, 78, 70, 37, 64, 9]
jumlah nilai tugas adalah 250

In [29]:
#bilangan ganjil
for i in nilaitugas:
    if i % 2 == 1:
        print(i)

85
93
47
63
85
85
89
59
9
47
31
11
57
67
67
65
23
73
45
87
49
67
73
45
11
27
51
23
45
55
15
21
45
19
91
49
21
89
17
13
33
77
99
83
87
55
65
89
79
19
65
93
33
99
79
51
57
65
5
45
33
15
95
67
27
7
41
91
23
97
43
39
47
43
63
93
91
15
51
79
71
33
77
69
83
61
55
57
35
11
55
33
63
15
21
89
31
53
35
25
93
53
45
69
79
69
47
19
5
83
25
37
9

In [35]:

for a in nilaitugas:
    if a > 70:
        print(a)

85
74
93
85
85
89
74
80
82
76
88
73
78
88
87
92
72
86
73
76
96
74
82
98
82
74
82
74
91
89
84
77
99
83
87
88
89
79
82
94
98
93
74
99
79
94
98
88
72
82
95
82
72
86
78
91
97
93
91
86
79
71
98
77
83
86
76
82
78
74
90
72
89
96
93
79
80
83
76
78

In [37]:
#mencari simpangan baku
#mencari total xi
x2=0
for x in nilaitugas:
    x = x2+ x
k = x**2
#mencari xi^2
for z in nilaitugas:
    y = 0
    z = y + (z**2)
#menghitung var dan stdev
var = ((len(nilaitugas)*k)-(z))/((len(nilaitugas))*((len(nilaitugas))-1))
stdev = var ** (1/2)
print('Standar deviasi yang diperoleh yaitu', stdev)

Standar deviasi yang diperoleh yaitu 0.5692099788303083

In [50]:
#menghitung nilai maksimum
maxs = nilaitugas[0]
for subs1 in nilaitugas:
    if maxs < subs1:
        maxs = subs1
print(maxs)
#menghitung nilai minimum
mins = nilaitugas[0]
for subs2 in nilaitugas:
    if mins > subs2:
        mins = subs2
print (mins)

99
2

In [57]:
# 5. Menghitung modus dari nilai 

#membuat dictionaries
book = {}
for frek in nilaitugas:
    if frek in book:
        book[frek] = book[frek] + 1
    else: 
        book[frek] = 1

#nyari nilai modus dgn cari paling tinggi value nya
high=0
mod = 0
for frek in book:
    if book[frek] > high:
        high = book[frek]
        mod = frek
        
print('modus yang diperoleh adalah', mod, 'yaitu', high)

modus yang diperoleh adalah 82 yaitu 8

In [58]:
paragraf = "Barcelona berhasil merebut posisi puncak klasemen La Liga Spanyol seusai menang 4-2 atas Sevilla pada pertandingan pekan kesembilan di Stadion Camp Nou, Sabtu (20/10/2018) atau Minggu dini hari WIB. Barcelona membuka keunggulan pada menit ke-2 melalui gol yang dicetak oleh Philippe Coutinho. Lionel Messi menggandakan keunggulan Barcelona, 10 menit berselang.  Namun, nahas bagi Barcelona, karena Messi harus ditarik keluar pada menit ke-26 setelah mengalami cedera. Tanpa Messi, skor 2-0 bertahan hingga babak pertama berakhir."
pisah = paragraf.split()
wordcount={}
for n in pisah:
    if n not in wordcount:
        wordcount[n] = 1
    else:
        wordcount[n] += 1
#print (wordcount)
for k,v in wordcount.items():
    print(k,v)

Barcelona 2
berhasil 1
merebut 1
posisi 1
puncak 1
klasemen 1
La 1
Liga 1
Spanyol 1
seusai 1
menang 1
4-2 1
atas 1
Sevilla 1
pada 3
pertandingan 1
pekan 1
kesembilan 1
di 1
Stadion 1
Camp 1
Nou, 1
Sabtu 1
(20/10/2018) 1
atau 1
Minggu 1
dini 1
hari 1
WIB. 1
membuka 1
keunggulan 2
menit 3
ke-2 1
melalui 1
gol 1
yang 1
dicetak 1
oleh 1
Philippe 1
Coutinho. 1
Lionel 1
Messi 2
menggandakan 1
Barcelona, 2
10 1
berselang. 1
Namun, 1
nahas 1
bagi 1
karena 1
harus 1
ditarik 1
keluar 1
ke-26 1
setelah 1
mengalami 1
cedera. 1
Tanpa 1
Messi, 1
skor 1
2-0 1
bertahan 1
hingga 1
babak 1
pertama 1
berakhir. 1